[package]
name = "mutex_rust"
version = "0.1.0"
authors = ["Jiaxiao Zhou <jiz417@ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
